# Generated by Django 4.2.4 on 2023-09-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ['name'], 'verbose_name': 'Red Social', 'verbose_name_plural': 'Redes Sociales'},
        ),
        migrations.AddField(
            model_name='social',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='social',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
    ]
